---
# tasks file for roles/rhel_install_nginx

# Подключаем официальный репозиторий nginx:
- name: add nginx repo
  yum_repository:
    name: nginx
    description: nginx official repo
    state: present
    baseurl: "http://nginx.org/packages/rhel/{{ansible_distribution_major_version}}/{{ansible_userspace_architecture}}/"
    gpgkey: http://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes

# Устанавливаем nginx:
- name: install nginx
  yum:
    name: nginx
    state: present
    update_cache: yes

# Создаём системные папки:
- name: create folders
  file:
    path: '/etc/nginx/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - conf-available
    - sites-available
    - sites-enabled

# Подключаем sites-enabled в конфиг nginx:
- name: enable sites-enabled dir
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: present
    insertafter: "(.*)include /etc/nginx/(.*)"
    line: " include /etc/nginx/sites-enabled/*.conf;"

# Определяем существует ли default.conf:
- name: stat /etc/nginx/conf.d/default.conf
  stat: path=/etc/nginx/conf.d/default.conf
  register: defaultconf_stat

# Если существует, перемещаем его:
- name: Move default.conf
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/sites-available/default.conf
  when: defaultconf_stat.stat.exists

# Добавляем в автозагрузку и стартуем вебсервер:
- name: enable and started nginx
  systemd:
    name: nginx.service
    enabled: yes
    state: started